#!/bin/bash

# A credential helper for git to retrieve usernames and passwords from bitwarden.
# For general usage, see https://git-scm.com/docs/gitcredentials.
# Here's a quick version:
# 1. Put this somewhere in your path (i.e. ~/.local/bin/git-credential-bw)
# 2. git config --global credential.helper bw
#
# based on https://github.com/lastpass/lastpass-cli/blob/master/contrib/examples/git-credential-lastpass
# Author: Marco Salathe
# Website: https://github.com/cosama/git-credential-bw

## Configurable Parameters:
# The port at which session key will be served
port="43211"

# Timeout after which the password needs to be entered again (seconds)
timeout=900


declare -A params

if [ "x$1" == "x-l" ]; then
    shift
    bwuser=$1
    shift
fi

if [ "x$1" == "xget" ]; then
    read line
    while [ -n "$line" ]; do
        key=${line%%=*}
        value=${line#*=}
        params[$key]=$value
        read line
    done

    if [ "x${params['protocol']}" != "xhttps" ]; then
        exit
    fi

    if [ -z "${params["host"]}" ]; then
        exit
    fi

    session=$(nc localhost $port < /dev/null 2> /dev/null)  #$(bw unlock --raw < /dev/tty)
    status=$?
    if [ $? -eq 0 ] || [ -n "${session}" ]; then
        bw --raw --session ${session} list items > /dev/null
        status=$?
    fi
    # echo "SESSION ${session}, $status" > /dev/stderr
    if [ $status -ne 0 ] || [ -z "${session}" ]; then
        session=$(bw unlock --raw < /dev/tty)
        if [ $? -ne 0 ]; then
            # echo "Failed, try again" > /dev/stderr
            session=$(bw login --raw < /dev/tty)
            if [ $? -ne 0 ]; then
                echo "Failed to login to bitwarden" > /dev/stderr
                exit
            fi
        fi
    fi
    # echo "Start server, credentials are ${session}" > /dev/stderr
    (((echo "${session}"; sleep 600 ; echo 'T' | nc -w 1 localhost $port > /dev/null) | nc -l localhost $port) 0<&- &>/dev/null &)

    user=`bw get --session ${session} --raw username ${params["host"]}`
    pass=`bw get --session ${session} --raw password ${params["host"]}`

    if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
        echo "Couldn't find host in bitwarden database." > /dev/stderr
        exit
    fi

    echo username=$user
    echo password=$pass
fi
